### ISSUE TITLE
 400 Bad Request (error code: 50006): Cannot send an empty message

### ISSUE THREAD

**Issue by vietrux** [mishalhossin/Discord-Chatbot-Gpt4Free#19]
I got this error when trying to run this app
```
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
```

**Comment by mishalhossin** [comment]
> I got this error when trying to run this app
> 
> ```
> discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
> ```

This error happens when you send 2nd message to the

There is probly a issue with `theb` but after sending the 3rd message the bot works like normal

**Comment by Moppel127** [comment]
same problem here, after the error message it also seems to always consider the penultimate message instead of the last one.

**Comment by Showdown76py** [comment]
Same here, the first message works perfectly. Then for the second message, it sends an empty message. And after it works but the responses are delayed (like he's answering for the precedent message

**Comment by mishalhossin** [comment]
Fixed 👍
