### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by villiam1999** [mishalhossin/Discord-Chatbot-Gpt4Free#20]
none

**Comment by villiam1999** [comment]
when trying to install with "pip3 install gpt4free" :

Collecting gpt4free
  Using cached gpt4free-1.0.2-py2.py3-none-any.whl (11 kB)
Collecting websocket-client (from gpt4free)
  Using cached websocket_client-1.5.1-py3-none-any.whl (55 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from gpt4free) (2.28.2)
Collecting tls-client (from gpt4free)
  Using cached tls_client-0.2.1-py3-none-any.whl (35.2 MB)
Collecting pypasser (from gpt4free)
  Using cached PyPasser-0.0.5.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mishalhossin** [comment]
The error message indicates that the **setuptools** package is missing in your build environment, which is required to install the package.

To fix this issue, you can try installing **setuptools** first and then attempt to install the **gpt4free** package again. Follow these steps:

1. Install setuptools using pip3:
```
pip3 install setuptools
```
2. After successfully installing **setuptools**, try installing the **gpt4free** package again:
 ```
 pip3 install gpt4free

 ```

**Comment by villiam1999** [comment]
> The error message indicates that the **setuptools** package is missing in your build environment, which is required to install the package.
> 
> To fix this issue, you can try installing **setuptools** first and then attempt to install the **gpt4free** package again. Follow these steps:
> 
> 1. Install setuptools using pip3:
> 
> ```
> pip3 install setuptools
> ```
> 
> 2. After successfully installing **setuptools**, try installing the **gpt4free** package again:
> 
> ```
> pip3 install gpt4free
> ```

I already tried pip3 install setuptools and still got this error

**Comment by mishalhossin** [comment]
- You can try upgrading pip using the following command:
```
pip3 install --upgrade pip
```
- try installing setuptools and gpt4free again:
```
pip3 install setuptools
pip3 install gpt4free
```

**Comment by villiam1999** [comment]
fixed
