### ISSUE TITLE
Bot keeps answering with loading page

### ISSUE THREAD

**Issue by TotoB12** [mishalhossin/Discord-Chatbot-Gpt4Free#3]
Every time I dm it, It replies the following code snippet:

<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/captcha/nojs/transparent.gif?ray=7c07752f7f44ad9b')"></div>
        <form id="challenge-form" action="/api/infer/answer?__cf_chl_f_tk=NBmvjrLKQxy4_dYp992RujCwUOsJ3CvNclpxk5hXlSk-1682938165-0-gaNycGzNDZA" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md"`

**Comment by localuser-isback** [comment]
> Every time I dm it, It replies the following code snippet:
> 
> <title>Just a moment...</title>
> Enable JavaScript and cookies to continue

Thats an issue with cloudflare make sure your useragent AND cf_clearance match that of what the bot is using!

**Comment by localuser-isback** [comment]
> > Every time I dm it, It replies the following code snippet:
> > <title>Just a moment...</title>
> > Enable JavaScript and cookies to continue
> 
> Thats an issue with cloudflare make sure your useragent AND cf_clearance match that of what the bot is using!

cf_clearance only lasts around 15-30 minutes aswell

**Comment by TotoB12** [comment]
got it, thanks

**Comment by mishalhossin** [comment]
I have replaced phind with theb
