### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by EnroXD1** [mishalhossin/Discord-Chatbot-Gpt4Free#30]
On some requests, the bot just crashes. Can you add an automatic restart of the bot after a crash?
![image](https://user-images.githubusercontent.com/49277608/236219077-ed0f9a62-15a3-4700-ad21-09e49c4bb516.png)

**Comment by mishalhossin** [comment]
Fixed 👍 thanks for creating issue
```
def handle_stream_response(response):
    Completion.message_queue.put(response.decode(errors='replace'))
```
This change will replace any invalid UTF-8 characters with the Unicode replacement character (U+FFFD) and should prevent the UnicodeDecodeError from occurring
