### ISSUE TITLE
 You are missing Administrator permission(s) to run this command.

### ISSUE THREAD

**Issue by yuyu1815** [mishalhossin/Discord-Chatbot-Gpt4Free#31]
![image](https://user-images.githubusercontent.com/83267351/236245653-3b65b897-c703-43bc-9673-ea0d2d042050.png)
Giving the administrator
But I get an error like the one above.
command : !toggleactive

**Comment by mishalhossin** [comment]
I added error handling to tell you that you don't have admin in the server
