### ISSUE TITLE
no module named "curl_cffi"

### ISSUE THREAD

**Issue by AreYouGoingToSanFransico** [mishalhossin/Discord-Chatbot-Gpt4Free#32]
Traceback (most recent call last):
  File "D:\idea\Discord-Chatbot-Gpt4Free-main\main.py", line 2, in <module>
    import theb
  File "D:\idea\Discord-Chatbot-Gpt4Free-main\theb\__init__.py", line 7, in <module>
    from curl_cffi import requests
ModuleNotFoundError: No module named 'curl_cffi'

yeah, I installed every module that in main.py with "import x" even curl_cffi, and this is not working, maybe im stupid or like that
discord token also taken from right place

**Comment by MDanyalT** [comment]
getting same problem

**Comment by yuyu1815** [comment]
Same for me.

**Comment by jtstroup** [comment]
Did you run the requirements command?

**Comment by mishalhossin** [comment]
run in cloned directory
```
pip install -r requirements.txt
```

**Comment by mishalhossin** [comment]
> > Did you run the requirements command?
> 
> yes, and still doesnt work

run `pip install curl_cffi`

**Comment by mashwishi** [comment]
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/62344860/77b45d4d-29fb-4db1-b896-f7af674c6c8b)
install it manually
