### ISSUE TITLE
GPT3.5 ?

### ISSUE THREAD

**Issue by yuyu1815** [mishalhossin/Discord-Chatbot-Gpt4Free#34]
![image](https://user-images.githubusercontent.com/83267351/236277613-04e7816b-88dd-4014-8a84-8d82d9a6f692.png)

Not gpt4?

**Comment by DaYzTm** [comment]
> ![image](https://user-images.githubusercontent.com/83267351/236277613-04e7816b-88dd-4014-8a84-8d82d9a6f692.png)
> 
> Not gpt4?

Dude, this is gpt-4, you entered a suboptimal prompt for testing. Dig into the code and you'll see that the gpt-4 model is connected there.

**Comment by yuyu1815** [comment]
Okay, thanks, I guess I misunderstood.
