### ISSUE TITLE
[enhancement] Proposal: Add support for discord's slash commands

### ISSUE THREAD

**Issue by antoKeinanen** [mishalhossin/Discord-Chatbot-Gpt4Free#41]
Add support for discord's slash commands. This would allow to use for example `/toggleactive` instead of `!toggleactive`. The `!` commands don't have to be removed for the slash commands to work. This would most likely be implemented by using `python.py`'s `@bot.hybrid_command()` [docs](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#hybrid-commands) decorator. If this is something you would like to be implemented you can assign this issue to me.

**Comment by antoKeinanen** [comment]
After looking at the source code I realized that you are already using hybrid_commad decorators. I propose that the readme.md should demostrate the ability to use slash commands.

**Comment by mishalhossin** [comment]
not yet i will have to add the hybrid command to the command tree
