### ISSUE TITLE
DO YOU GUYS WANT IMAGE DETECTION ?

### ISSUE THREAD

**Issue by mishalhossin** [mishalhossin/Discord-Chatbot-Gpt4Free#43]
![image](https://user-images.githubusercontent.com/91066601/236655115-4c2c1179-02e9-499d-898a-08a0213c52ca.png)

**Comment by Zalatis** [comment]
Would be nice !

**Comment by mishalhossin** [comment]
> Would be nice !

yea added it rn

**Comment by KZkici** [comment]
Seems when i paste the image as link it works, but when its posted as an image attachment it doesn't

**Comment by mishalhossin** [comment]
> Seems when i paste the image as link it works, but when its posted as an image attachment it doesn't

Yea i used a very very heavy model before

**Comment by mishalhossin** [comment]
it works with images and links

**Comment by KZkici** [comment]
Stopped the service, pulled changes just in case, tested and:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/23621231/236683666-20e1e452-ca7b-4312-b4e1-390b08367784.png">

No response after attachment, above you can see it responds with link

**Comment by mishalhossin** [comment]
Edit line 44 ```py
API_URL = "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-base" #Use this if slow https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning
```

**Comment by mishalhossin** [comment]
works tho

![image](https://user-images.githubusercontent.com/91066601/236683937-a68b1aca-d92d-412d-9b9c-cb4b800957b7.png)

**Comment by mishalhossin** [comment]
made the image detection better by using 4 image to text model 
```py
API_URLS = [
    "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large",
    "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-base",
    "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning",
    "https://api-inference.huggingface.co/models/ydshieh/vit-gpt2-coco-en"
]
```
