### ISSUE TITLE
Why the bot answer me keep accumulating？

### ISSUE THREAD

**Issue by dadaoerv** [mishalhossin/Discord-Chatbot-Gpt4Free#45]
Q1............
A1.............
Q2.................
A1..............
A2...............
Q3................
A1......
A2...........
A3............

**Comment by mishalhossin** [comment]
Try lowering this 
![image](https://user-images.githubusercontent.com/91066601/236673966-9243edbd-ce72-4aa2-9491-4d96cf068888.png)
