### ISSUE TITLE
[FEATURE REQUEST] Make bot respond only on replies or tag

### ISSUE THREAD

**Issue by Dhruvgera** [mishalhossin/Discord-Chatbot-Gpt4Free#51]
Bot responding to every message causes troubles, if its possible to make it such that it only responds to replies or tags would be helpful

**Comment by mishalhossin** [comment]
> Bot responding to every message causes troubles, if its possible to make it such that it only responds to replies or tags would be helpful

Alright

**Comment by mishalhossin** [comment]
I will make it so its always active in active_channels and you can tag or reply by default

**Comment by Dhruvgera** [comment]
> I will make it so its always active in active_channels and you can tag or reply by default

Yes, thank you very much, current behavior replies to even normal conversation between users causing spam and confusion

**Comment by mishalhossin** [comment]
made the bot ignore message if you are replying to someone
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/91066601/8bf8d634-4793-4b05-9a83-5e14ee152863)

**Comment by Dhruvgera** [comment]
Works, thanks a lot!

**Comment by Dhruvgera** [comment]
Bug spotted: Bot will sometimes not reply in channel, but instead respond in DMs about the asked question

**Comment by mishalhossin** [comment]
> Bug spotted: Bot will sometimes not reply in channel, but instead respond in DMs about the asked question

what okay

**Comment by mishalhossin** [comment]
Do you know how to reproduce it ?

**Comment by Dhruvgera** [comment]
> Do you know how to reproduce it ?

It happens every time, bot doesn't respond till you give it the next message or ask it in DMs. Then it replies to the previous question and the current question simultaneously

**Comment by mishalhossin** [comment]
> > Do you know how to reproduce it ?
> 
> It happens every time, bot doesn't respond till you give it the next message or ask it in DMs. Then it replies to the previous question and the current question simultaneously

Its really fucking broken i will add the feature later

**Comment by Dhruvgera** [comment]
> > > Do you know how to reproduce it ?
> > 
> > 
> > It happens every time, bot doesn't respond till you give it the next message or ask it in DMs. Then it replies to the previous question and the current question simultaneously
> 
> Its really fucking broken i will add the feature later

Is the current repo stable then? Should I pull and merge?

**Comment by mishalhossin** [comment]
> Is the current repo stable then? Should I pull and merge?

i guess
