### ISSUE TITLE
bot doesnt understand the picture I provided

### ISSUE THREAD

**Issue by AmirulAndalib** [mishalhossin/Discord-Chatbot-Gpt4Free#52]
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/86344856/836dbe33-e52a-4611-9fb6-0d62c4f28ded)

**Comment by mishalhossin** [comment]
maybe the image is too large and besides that it cant see a whole graph

**Comment by mishalhossin** [comment]
Yea its a issue with hugging face

**Comment by mishalhossin** [comment]
My bad for closing this

**Comment by mishalhossin** [comment]
Its problem with hugginface

![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/91066601/0c82f081-dade-4036-a885-cc9607fe8e39)

**Comment by RicardoVMon** [comment]
> Its problem with hugginface
> 
> ![image](https://user-images.githubusercontent.com/91066601/237090623-0c82f081-dade-4036-a885-cc9607fe8e39.png)

Yeah, that's exactly the error that is telling me, every time i send a picture the console says: Authorization header is correct, but token seems invalid. Will look into it to see if I can help

**Comment by mishalhossin** [comment]
Its now fixed tho
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/91066601/0c34e6aa-b34f-4810-8543-01764d4e4b1a)

**Comment by AmirulAndalib** [comment]
thanks it works
