### ISSUE TITLE
i cant use /toggleactive

### ISSUE THREAD

**Issue by Ancient-Lamp** [mishalhossin/Discord-Chatbot-Gpt4Free#54]
when i try to enable the bot in a channel it returns nothing:
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/125932358/6c9e33fb-65de-4fa3-ab9e-3755cb646089)
and says permission denied in the console:
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/125932358/420dcf19-bd13-476c-870a-55452c3746f0)
Even though it has the administrator permission:
![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/125932358/1aeb0074-d0f4-4359-a43a-b80a7ee03a4f)
I tried modifying some code and some settings but nothing changes.

**Comment by mishalhossin** [comment]
BRUH CAN YOU SEE THE INVITE LINK IN CONSOLE ? USE THAT

![image](https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/assets/91066601/2f9f9264-ab75-4adf-9150-b724fee7f0a0)

**Comment by Ancient-Lamp** [comment]
I have invited it trough the link, I gave it administrator, I almost gave the server ownership, and it still does not work.
