### ISSUE TITLE
A question about you

### ISSUE THREAD

**Issue by nacho00112** [mishalhossin/Discord-Chatbot-Gpt4Free#57]
You really have 15 years of age? Your programmation is too good so that would be amazing

**Comment by mishalhossin** [comment]
Ikr I'm awesome

**Comment by FBY007** [comment]
When I input `python main.py` it tell me:`Traceback`` (most recent call last):
  File "E:\Discord-Chatbot-Gpt4Free\main.py", line 62, in <module>
    api_key = os.environ['HUGGING_FACE_API']
  File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HUGGING_FACE_API'
`
And I checked my Hugging Face API it doesn't have any problem. I don't know why.

**Comment by nacho00112** [comment]
> Ikr I'm awesome

How you learned that programming skills?

**Comment by nacho00112** [comment]
> When I input `python main.py` it tell me:`` Traceback`` (most recent call last): File "E:\Discord-Chatbot-Gpt4Free\main.py", line 62, in <module> api_key = os.environ['HUGGING_FACE_API'] File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\os.py", line 679, in __getitem__ raise KeyError(key) from None KeyError: 'HUGGING_FACE_API' `` And I checked my Hugging Face API it doesn't have any problem. I don't know why.

It's the `HUGGING_FACE_API` environment variable that cannot be encountered, this command should solve the problem:
`printf "\nexport HUGGING_FACE_API='REPLACE_THIS_WITH_YOUR_API_KEY'\n" >> ~/.bashrc; source ~/.bashrc`

**Comment by mishalhossin** [comment]
> > When I input `python main.py` it tell me:` Traceback` (most recent call last): File "E:\Discord-Chatbot-Gpt4Free\main.py", line 62, in  api_key = os.environ['HUGGING_FACE_API'] File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\os.py", line 679, in **getitem** raise KeyError(key) from None KeyError: 'HUGGING_FACE_API' `` And I checked my Hugging Face API it doesn't have any problem. I don't know why.
> 
> It's the `HUGGING_FACE_API` environment variable that cannot be encountered, this command should solve the problem permanently:
> 
> ```shell
> printf "\nexport HUGGING_FACE_API='REPLACE_THIS_WITH_YOUR_API_KEY'\n" >> ~/.bashrc; source ~/.bashrc
> ```

As i can see he is on windows

**Comment by nacho00112** [comment]
> > > When I input `python main.py` it tell me:` Traceback` (most recent call last): File "E:\Discord-Chatbot-Gpt4Free\main.py", line 62, in  api_key = os.environ['HUGGING_FACE_API'] File "E:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\os.py", line 679, in **getitem** raise KeyError(key) from None KeyError: 'HUGGING_FACE_API' `` And I checked my Hugging Face API it doesn't have any problem. I don't know why.
> > 
> > 
> > It's the `HUGGING_FACE_API` environment variable that cannot be encountered, this command should solve the problem permanently:
> > ```shell
> > printf "\nexport HUGGING_FACE_API='REPLACE_THIS_WITH_YOUR_API_KEY'\n" >> ~/.bashrc; source ~/.bashrc
> > ```
> 
> As i can see he is on windows

Oh i ignored that completely haha, i investigated and on the windows cmd it is:
```cmd
SETX HUGGING_FACE_API REPLACE_THIS_WITH_YOUR_API_KEY
```
On PowerShell:
```powershell
[System.Environment]::SetEnvironmentVariable('HUGGING_FACE_API','REPLACE_THIS_WITH_YOUR_API_KEY')
```
