### ISSUE TITLE
the bot isn't answering

### ISSUE THREAD

**Issue by mishalhossin** [mishalhossin/Discord-Chatbot-Gpt4Free#61]
### Discussed in https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **saaandrew** May 13, 2023</sup>
hey so i was using your code to run my bot on repl but when i DM it, the bot just "..... is typing" then nothing. absolute nothing.
i think it's generating the answer so i let it there but more than 30mins later still nothing. i check in the console and it still fine, no errors.
If mishal have a fix please answer me.</div>

**Comment by bhaskoro-muthohar** [comment]
discussion #60 seems to be deleted.

**Comment by PigmaTop** [comment]
I have the same problem
