### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bolavefasfas** [mishalhossin/Discord-Chatbot-Gpt4Free#7]
for linux
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from gpt4free import theb
  File "/root/Discord-Chatbot-Gpt4Free/gpt4free/__init__.py", line 3, in <module>
    from gpt4free import cocalc
ImportError: cannot import name 'cocalc' from partially initialized module 'gpt4free' (most likely due to a circular import) (/root/Discord-Chatbot-Gpt4Free/gpt4free/__init__.py)
```

For winodws 
```
PS C:\Users\james\PycharmProjects\discord_gpt\Discord-Chatbot-Gpt4Free> py main.py
Traceback (most recent call last):
  File "C:\Users\james\PycharmProjects\discord_gpt\Discord-Chatbot-Gpt4Free\main.py", line 2, in <module>
    from gpt4free import theb
  File "C:\Users\james\PycharmProjects\discord_gpt\Discord-Chatbot-Gpt4Free\gpt4free\__init__.py", line 3, in <module>
    from gpt4free import cocalc
ImportError: cannot import name 'cocalc' from partially initialized module 'gpt4free' (most likely due to a circular import) (C:\Users\james\PycharmProjects\discord_gpt\Discord-Chatbot-Gpt4Free\gpt4free\__init__.py)
```
Inside docker-container
```
discordgptbot | Traceback (most recent call last):
discordgptbot |   File "main.py", line 2, in <module>
discordgptbot |     from gpt4free import theb
discordgptbot |   File "/app/gpt4free/__init__.py", line 3, in <module>
discordgptbot |     from gpt4free import cocalc
discordgptbot | ImportError: cannot import name 'cocalc' from partially initialized module 'gpt4free' (most likely due to a circular import) (/app/gpt4free/__init__.py)
discordgptbot exited with code 1
```

Can can you make a telegram bot also it would be helpful as many people also use telegram 
And the b is gpt3.5 right ?

**Comment by Rithmatist** [comment]
I am having the same issue.

**Comment by TotoB12** [comment]
works very well on replit

**Comment by wthee00** [comment]
same problem

**Comment by Nxqz** [comment]
Don't work on replit 
![image](https://user-images.githubusercontent.com/130841479/235519895-e72f7f52-c76e-4d6f-aec2-56d3b7612c0f.png)

**Comment by TotoB12** [comment]
just two command in shell:
`pip install cocal`
+ the next error you will get, I forgot the name package, but it will say it cannot import name "name"

**Comment by maha-20** [comment]
Hey everyone, im having the same issue.

@TotoB12 
> just two command in shell: `pip install cocal` ++ the next error you will get, I forgot the name package, but it will say it cannot import name "name"

Did not work for me. Could not even `pip install cocalc`.
I tried removing cocalc from `gpt4free/__init__.py`, then i got the same error with forefront. This time `pip install forefront` worked, but after running it i keep getting the same error with forefront.

**Comment by mishalhossin** [comment]
i updated gpt4free package it now only needs theb

**Comment by devnandan234x** [comment]
> i updated gpt4free package it now. only needs `theb`

About the version of gpt theb uses is it 3.5 or 4

**Comment by bolavefasfas** [comment]
> i updated gpt4free package it now. only needs `theb`

Can can you make a telegram bot also it would be helpful as many people also use telegram

**Comment by mishalhossin** [comment]
> About the version of gpt theb uses is it 3.5 or 4

I might update to forefront but it might give slow resposne

**Comment by mishalhossin** [comment]
> Can can you make a telegram bot also it would be helpful as many people also use telegram

I will look into it as i never built a telegram bot
